drop database if exists requisitos;
CREATE DATABASE requisitos;
USE requisitos;

CREATE TABLE sistemas( 
bome VARCHAR (50) NOT NULL,
IdNegocios INT PRIMARY KEY ,
requisito VARCHAR (100) NOT NULL,
prioridade int (5) NOT NULL
);

INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ("yasmin","201", "Cadastro de livros com todos os detalhes","2");
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ("julia","202", "Pesquisa de livros por título autor ou categoria","5");
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ("rafaela","203", "Controle de empréstimo e devoluções","5");
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ("rodrigo","204", "Cadastro de usuários","5");
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ("lais","205", "Geração de relatórios automáticos","4");
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Fushiguro', 1, 'Curiosidade pessoal', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Araragi', 2, 'Trabalho de faculdade', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Kamado', 3, 'Curiosidade pessoal', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Yukio Kaname', 4, 'Curiosidade pessoal', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kurt Hoshigaki', 5, 'Preparação para concurso', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jean Fushiguro', 6, 'Revisão de conteúdo', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Todoroki', 7, 'Aprimorar vocabulário', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Gabby Yagami', 8, 'Preparação para concurso', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Bobby Kamado', 9, 'Revisão de conteúdo', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Charles Uzumaki', 10, 'Projeto escolar', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Bobby Kamado', 11, 'Aprimorar vocabulário', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Araragi', 12, 'Curiosidade pessoal', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jean Satou', 13, 'Projeto escolar', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kurt Asta', 14, 'Leitura de lazer', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Levi', 15, 'Revisão de conteúdo', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Yukio Hoshigaki', 16, 'Curiosidade pessoal', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Satou', 17, 'Pesquisa acadêmica', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Lorna Ayanami', 18, 'Leitura de lazer', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Kamado', 19, 'Preparação para concurso', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Yukio Shiba', 20, 'Estudo para provas', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Charles Kamado', 21, 'Leitura de lazer', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jubilee Todoroki', 22, 'Aprimorar vocabulário', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Todoroki', 23, 'Curiosidade pessoal', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Zoldyck', 24, 'Curiosidade pessoal', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Charles Gojo', 25, 'Leitura de lazer', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Kamui', 26, 'Curiosidade pessoal', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Raven Asta', 27, 'Recomendação de professor', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Raven Asta', 28, 'Estudo para provas', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Kamado', 29, 'Curiosidade pessoal', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jubilee Kaname', 30, 'Pesquisa acadêmica', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Lorna Todoroki', 31, 'Curiosidade pessoal', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Gabby Shiba', 32, 'Preparação para concurso', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Shiba', 33, 'Preparação para concurso', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Satou', 34, 'Aprimorar vocabulário', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Levi', 35, 'Preparação para concurso', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Kamado', 36, 'Recomendação de professor', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Gabby Kaname', 37, 'Aprimorar vocabulário', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jean Levi', 38, 'Projeto escolar', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Peter Zoldyck', 39, 'Preparação para concurso', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Uzumaki', 40, 'Estudo para provas', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Bobby Tohsaka', 41, 'Preparação para concurso', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Tohsaka', 42, 'Projeto escolar', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Kamui', 43, 'Revisão de conteúdo', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Raven Yagami', 44, 'Recomendação de professor', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Logan Zoldyck', 45, 'Revisão de conteúdo', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Logan Okabe', 46, 'Curiosidade pessoal', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Logan Todoroki', 47, 'Preparação para concurso', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kurt Satou', 48, 'Curiosidade pessoal', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Raven Kaname', 49, 'Trabalho de faculdade', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Scott Uzumaki', 50, 'Projeto escolar', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Scott Kamui', 51, 'Leitura de lazer', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kurt Abarai', 52, 'Leitura de lazer', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Peter Gojo', 53, 'Recomendação de professor', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Lorna Araragi', 54, 'Leitura de lazer', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Kaname', 55, 'Projeto escolar', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Kamado', 56, 'Revisão de conteúdo', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kitty Asta', 57, 'Preparação para concurso', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kurt Kamui', 58, 'Aprimorar vocabulário', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Zoldyck', 59, 'Projeto escolar', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Yukio Okabe', 60, 'Pesquisa acadêmica', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Logan Kamui', 61, 'Projeto escolar', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Logan Kaname', 62, 'Trabalho de faculdade', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Scott Zoldyck', 63, 'Pesquisa acadêmica', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Peter Ayanami', 64, 'Projeto escolar', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Zoldyck', 65, 'Pesquisa acadêmica', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Abarai', 66, 'Estudo para provas', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Peter Zoldyck', 67, 'Estudo para provas', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Levi', 68, 'Trabalho de faculdade', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Ororo Fushiguro', 69, 'Leitura de lazer', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Peter Gojo', 70, 'Estudo para provas', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Charles Tohsaka', 71, 'Revisão de conteúdo', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Yagami', 72, 'Preparação para concurso', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Gabby Ayanami', 73, 'Curiosidade pessoal', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Tohsaka', 74, 'Trabalho de faculdade', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Gabby Hoshigaki', 75, 'Aprimorar vocabulário', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Abarai', 76, 'Recomendação de professor', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Yukio Hoshigaki', 77, 'Pesquisa acadêmica', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Todoroki', 78, 'Revisão de conteúdo', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Lorna Kamado', 79, 'Projeto escolar', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Araragi', 80, 'Aprimorar vocabulário', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Fushiguro', 81, 'Estudo para provas', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Raven Kamui', 82, 'Aprimorar vocabulário', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Logan Asta', 83, 'Recomendação de professor', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Lorna Zoldyck', 84, 'Trabalho de faculdade', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Logan Araragi', 85, 'Estudo para provas', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Lorna Okabe', 86, 'Estudo para provas', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Abarai', 87, 'Aprimorar vocabulário', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Abarai', 88, 'Recomendação de professor', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Zoldyck', 89, 'Preparação para concurso', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Okabe', 90, 'Leitura de lazer', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Logan Abarai', 91, 'Trabalho de faculdade', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kurt Tohsaka', 92, 'Trabalho de faculdade', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kurt Fushiguro', 93, 'Preparação para concurso', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Bobby Ayanami', 94, 'Revisão de conteúdo', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Charles Kamado', 95, 'Projeto escolar', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jean Shiba', 96, 'Curiosidade pessoal', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Ayanami', 97, 'Preparação para concurso', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Tohsaka', 98, 'Pesquisa acadêmica', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Kamui', 99, 'Estudo para provas', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Peter Kamui', 100, 'Leitura de lazer', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Erik Okabe', 101, 'Trabalho de faculdade', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Uzumaki', 102, 'Revisão de conteúdo', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Erik Todoroki', 103, 'Estudo para provas', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jean Gojo', 104, 'Trabalho de faculdade', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Bobby Kamado', 105, 'Revisão de conteúdo', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Zoldyck', 106, 'Aprimorar vocabulário', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kitty Zoldyck', 107, 'Aprimorar vocabulário', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Scott Tohsaka', 108, 'Estudo para provas', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Charles Kaname', 109, 'Curiosidade pessoal', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jubilee Ayanami', 110, 'Aprimorar vocabulário', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Raven Todoroki', 111, 'Curiosidade pessoal', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jean Uzumaki', 112, 'Pesquisa acadêmica', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Raven Zoldyck', 113, 'Trabalho de faculdade', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Lorna Okabe', 114, 'Aprimorar vocabulário', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Kamado', 115, 'Recomendação de professor', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Ororo Gojo', 116, 'Estudo para provas', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kurt Levi', 117, 'Trabalho de faculdade', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Lorna Uzumaki', 118, 'Recomendação de professor', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Bobby Ayanami', 119, 'Estudo para provas', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Raven Hoshigaki', 120, 'Aprimorar vocabulário', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jean Kaname', 121, 'Pesquisa acadêmica', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Peter Shiba', 122, 'Trabalho de faculdade', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Satou', 123, 'Recomendação de professor', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Hoshigaki', 124, 'Curiosidade pessoal', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Fushiguro', 125, 'Curiosidade pessoal', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jean Satou', 126, 'Estudo para provas', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jean Kamado', 127, 'Preparação para concurso', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Tohsaka', 128, 'Revisão de conteúdo', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Gabby Kamado', 129, 'Revisão de conteúdo', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Erik Abarai', 130, 'Curiosidade pessoal', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Kamado', 131, 'Curiosidade pessoal', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Ororo Ayanami', 132, 'Curiosidade pessoal', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Scott Levi', 133, 'Projeto escolar', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Scott Levi', 134, 'Trabalho de faculdade', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Araragi', 135, 'Leitura de lazer', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Abarai', 136, 'Revisão de conteúdo', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Fushiguro', 137, 'Recomendação de professor', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Charles Abarai', 138, 'Preparação para concurso', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Bobby Fushiguro', 139, 'Curiosidade pessoal', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jubilee Satou', 140, 'Recomendação de professor', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Erik Shiba', 141, 'Pesquisa acadêmica', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Kamado', 142, 'Preparação para concurso', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Peter Araragi', 143, 'Preparação para concurso', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Kamado', 144, 'Estudo para provas', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kitty Shiba', 145, 'Aprimorar vocabulário', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Hoshigaki', 146, 'Projeto escolar', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Gabby Okabe', 147, 'Aprimorar vocabulário', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kitty Zoldyck', 148, 'Aprimorar vocabulário', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Erik Shiba', 149, 'Projeto escolar', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Levi', 150, 'Recomendação de professor', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Asta', 151, 'Estudo para provas', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Yukio Ayanami', 152, 'Estudo para provas', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jubilee Shiba', 153, 'Leitura de lazer', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Yukio Hoshigaki', 154, 'Leitura de lazer', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Logan Yagami', 155, 'Curiosidade pessoal', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Lorna Shiba', 156, 'Curiosidade pessoal', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Gabby Abarai', 157, 'Recomendação de professor', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Yukio Kamado', 158, 'Recomendação de professor', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Scott Fushiguro', 159, 'Recomendação de professor', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Asta', 160, 'Revisão de conteúdo', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Raven Satou', 161, 'Leitura de lazer', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Bobby Okabe', 162, 'Trabalho de faculdade', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Erik Kamado', 163, 'Aprimorar vocabulário', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Gabby Kamado', 164, 'Revisão de conteúdo', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Hoshigaki', 165, 'Revisão de conteúdo', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Satou', 166, 'Trabalho de faculdade', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Yukio Yagami', 167, 'Projeto escolar', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Yukio Kamado', 168, 'Preparação para concurso', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Lorna Todoroki', 169, 'Projeto escolar', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kurt Okabe', 170, 'Aprimorar vocabulário', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Fushiguro', 171, 'Aprimorar vocabulário', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Ororo Abarai', 172, 'Revisão de conteúdo', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Hank Zoldyck', 173, 'Estudo para provas', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Scott Zoldyck', 174, 'Preparação para concurso', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Yagami', 175, 'Preparação para concurso', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kitty Abarai', 176, 'Preparação para concurso', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Peter Araragi', 177, 'Revisão de conteúdo', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Warren Levi', 178, 'Aprimorar vocabulário', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Raven Todoroki', 179, 'Curiosidade pessoal', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Kitty Todoroki', 180, 'Trabalho de faculdade', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Charles Satou', 181, 'Preparação para concurso', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Jean Kamado', 182, 'Revisão de conteúdo', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Erik Tohsaka', 183, 'Projeto escolar', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Gabby Kamado', 184, 'Projeto escolar', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Ororo Satou', 185, 'Preparação para concurso', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Scott Okabe', 186, 'Pesquisa acadêmica', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Bobby Kamado', 187, 'Aprimorar vocabulário', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Raven Fushiguro', 188, 'Curiosidade pessoal', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Ororo Gojo', 189, 'Estudo para provas', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Logan Asta', 190, 'Trabalho de faculdade', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Peter Araragi', 191, 'Curiosidade pessoal', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Alex Kaname', 192, 'Aprimorar vocabulário', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Peter Shiba', 193, 'Preparação para concurso', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Kamui', 194, 'Trabalho de faculdade', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Erik Hoshigaki', 195, 'Curiosidade pessoal', '3');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Charles Fushiguro', 196, 'Aprimorar vocabulário', '4');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Charles Gojo', 197, 'Trabalho de faculdade', '5');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Emma Zoldyck', 198, 'Trabalho de faculdade', '1');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Logan Kamado', 199, 'Projeto escolar', '2');
INSERT INTO sistemas (bome, IdNegocios, requisito, prioridade) VALUES ('Laura Satou', 200, 'Curiosidade pessoal', '3');